# Generated by Django 3.1.13 on 2021-09-14 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[(0, 'Low'), (3, 'Normal'), (4, 'High')], default=3, max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[(0, 'Low'), (3, 'Normal'), (4, 'High')], default=3, max_length=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_size', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayResolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DisplayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[(0, 'Low'), (3, 'Normal'), (4, 'High')], default=3, max_length=6)),
                ('year', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[(0, 'Low'), (3, 'Normal'), (4, 'High')], default=3, max_length=6)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('front_camera', models.CharField(blank=True, max_length=50)),
                ('sim_amount', models.PositiveIntegerField()),
                ('main_camera', models.CharField(blank=True, max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_brand', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.color')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_cpu', to='products.cpu')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.display')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_gpu', to='products.cpu')),
                ('image', models.ManyToManyField(related_name='phone_images', to='products.Image')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('series', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.series')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.storage')),
                ('unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[(0, 'Low'), (3, 'Normal'), (4, 'High')], default=3, max_length=6)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
                ('front_camera', models.CharField(blank=True, max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_brand', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.color')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_cpu', to='products.cpu')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.display')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebook_gpu', to='products.cpu')),
                ('image', models.ManyToManyField(related_name='notebook_images', to='products.Image')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('series', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.series')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.storage')),
                ('unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
        migrations.AddField(
            model_name='display',
            name='display_resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.displayresolution'),
        ),
        migrations.AddField(
            model_name='display',
            name='display_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.displaytype'),
        ),
    ]
