# Generated by Django 3.1.13 on 2021-09-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
