# Generated by Django 3.1.13 on 2021-09-14 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210914_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.series'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.series'),
        ),
    ]
