# Generated by Django 3.1.13 on 2021-09-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210914_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
