# Generated by Django 3.1.13 on 2021-12-01 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_os_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeLaptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('front_camera', models.CharField(blank=True, max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttypelaptop_brand', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.color')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttypelaptop_cpu', to='products.cpu')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.display')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttypelaptop_gpu', to='products.gpu')),
                ('image', models.ManyToManyField(related_name='producttypelaptop_images', to='products.Image')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.os')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.series')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.storage')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unit')),
            ],
            options={
                'verbose_name': 'Laptop',
                'verbose_name_plural': 'Laptops',
            },
        ),
        migrations.CreateModel(
            name='ProductTypePhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2)),
                ('description', models.CharField(max_length=1000)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('front_camera', models.CharField(blank=True, max_length=50)),
                ('sim_amount', models.PositiveIntegerField()),
                ('main_camera', models.CharField(blank=True, max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttypephone_brand', to='products.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.color')),
                ('cpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttypephone_cpu', to='products.cpu')),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.display')),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttypephone_gpu', to='products.gpu')),
                ('image', models.ManyToManyField(related_name='producttypephone_images', to='products.Image')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.os')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.series')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.storage')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.unit')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
        migrations.RemoveField(
            model_name='phone',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='category',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='color',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='display',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='os',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='series',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='unit',
        ),
        migrations.DeleteModel(
            name='Notebook',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
